FROM node:20-alpine

RUN addgroup -g 1001 -S nodegroup && \
    adduser -S -u 1001 -G nodegroup nodeuser

WORKDIR /app

COPY server.js ./

RUN chown -R nodeuser:nodegroup /app

USER nodeuser

EXPOSE 3000

CMD ["node", "server.js"]